# Generated by Django 4.0.8 on 2023-09-30 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0002_remove_customuser_username_customuser_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'NewUser', 'verbose_name_plural': 'NewUsers'},
        ),
    ]
