# Generated by Django 4.0.8 on 2023-11-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackrecord',
            name='Track_Amount',
            field=models.IntegerField(verbose_name='TrackAmount'),
        ),
    ]
