# Generated by Django 4.0.8 on 2024-05-31 06:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('Credit_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='CreditID')),
                ('CreditCard_Name', models.CharField(default='Pay in Cash(付現)', max_length=50)),
                ('CreditCard_Detail', models.CharField(default='test', max_length=50)),
                ('CreditCard_PayDate', models.DateField(blank=True, default=datetime.date.today)),
                ('User_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomUser_CreditCard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackType',
            fields=[
                ('Type_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='TypeID')),
                ('Spend_Type', models.CharField(default='Cost of Living(生活費)', max_length=50)),
                ('User_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomUser_TrackType', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackRecord',
            fields=[
                ('Track_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='TrackID')),
                ('Track_Amount', models.IntegerField(verbose_name='TrackAmount')),
                ('Track_Detail', models.CharField(max_length=100, verbose_name='TrackDetail')),
                ('Track_Date', models.DateField(default=datetime.date.today, verbose_name='TrackDate')),
                ('Credit_Card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Track.creditcard', verbose_name='CreditCard')),
                ('Track_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Track.tracktype', verbose_name='TrackType')),
                ('User_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomUser_TrackRecord', to=settings.AUTH_USER_MODEL, verbose_name='CustomUser')),
            ],
        ),
    ]
