# Generated by Django 4.0.8 on 2024-06-08 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackrecord',
            name='Credit_Card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Track.creditcard', verbose_name='CreditCard'),
        ),
    ]
