# Generated by Django 4.0.8 on 2024-06-10 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0003_alter_trackrecord_credit_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackrecord',
            name='Credit_Card',
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
