# Generated by Django 4.0.8 on 2024-07-21 15:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Track', '0004_remove_trackrecord_credit_card_delete_creditcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('Credit_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='CreditID')),
                ('CreditCard_Name', models.CharField(default='Pay in Cash(付現)', max_length=50)),
                ('CreditCard_Detail', models.CharField(default='test', max_length=50)),
                ('CreditCard_PayDate', models.DateField(blank=True, default=datetime.date.today)),
                ('User_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomUser_CreditCard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
